# Test this without rebuilding the docker image $> docker-compose up
# Test this with rebuilding the docker image $> docker-compose up --build

version: '3'

services:
  pubsubagent:
    build:
      context: .
      dockerfile: Dockerfile
    image: csci652:latest
    networks:
      - csci652network
    command:
      - /bin/bash
      - -c
      - |
        echo "Initialize pubsubagent...done!"
        tail -f /dev/null



networks:
  csci652network: