# Test this without rebuilding the docker image $> docker-compose up
# Test this with rebuilding the docker image $> docker-compose up --build

version: '3'

services:
  EventManager:
    build:
      context: .
      dockerfile: Dockerfile
    image: csci652:latest
    container_name: EventManager
    networks:
      - csci652network
    command:
      - /bin/bash
      - -c
      - |
        cd project2
        java -cp target/project2-1.0-SNAPSHOT.jar edu.rit.cs.EventManager
        echo "Initialize pubsubagent...done!"
        tail -f /dev/null

  PubSub:
    image: csci652:latest
    container_name: PubSub
    networks:
      - csci652network
    depends_on:
      - EventManager
    command:
      - /bin/bash
      - -c
      - |
        cd project2
        echo "Initialize pubsubagent...done!"
        tail -f /dev/null

networks:
  csci652network: