# Test this without rebuilding the docker image $> docker-compose up
# Test this with rebuilding the docker image $> docker-compose up --build

version: '3.7'

services:
  peer1:
    build:
      context: .
      dockerfile: Dockerfile
    image: csci652:latest
    container_name: peer1
    working_dir: /csci652
    networks:
      - csci652network
    ports:
      - 9091
      - 9092
      - 9093
    command:
      - /bin/bash
      - -c
      - |
        echo "Initialize peer1...done!"
        tail -f /dev/null


  peer2:
    image: csci652:latest
    container_name: peer2
    depends_on:
      - peer1
    working_dir: /csci652
    networks:
      - csci652network
    ports:
      - 9091
      - 9092
      - 9093
    command:
      - /bin/bash
      - -c
      - |
        echo "Initialize peer2...done!"
        tail -f /dev/null

  rmiserver:
    image: csci652:latest
    container_name: rmiserver
    depends_on:
      - peer1
    working_dir: /csci652/remote_procedure_call
    networks:
      - csci652network
    ports:
      - 1099
    command:
      - /bin/bash
      - -c
      - |
        java -cp target/remote_procedure_call-1.0-SNAPSHOT.jar edu.rit.cs.JsonRPCServer
        echo "Initialize rmiserver...done!"
        tail -f /dev/null

  rmiclient:
    image: csci652:latest
    container_name: rmiclient
    depends_on:
      - rmiserver
    working_dir: /csci652/remote_procedure_call
    networks:
    - csci652network
    command:
      - /bin/bash
      - -c
      - |
        java -cp target/remote_procedure_call-1.0-SNAPSHOT.jar edu.rit.cs.JsonRPCClient rmiserver:9091
        tail -f /dev/null



networks:
  csci652network: